name: Build & Publish Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Install minikube dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat curl

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for service to be ready
        run: |
          echo "Waiting for pods..."
          kubectl rollout status deployment/python-api --timeout=60s

      - name: Port-forward and test endpoints
        run: |
          kubectl port-forward svc/python-api-service 8080:80 &
          sleep 5
          curl http://localhost:8080/terms
          curl http://localhost:8080/definitions\?term=person
